name: veda-egypt
on: 
  push:
    branch: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.veda-egypt.com
      uses: appleboy/ssh-action@master
      with:
        host: www.veda-egypt.com
        username: root
        key: ${{ secrets.TF_SECRET }}
        port: 22
        script: |
          cd /opt/www_veda-egypt_com/
          git log -1
          git pull
